### ISSUE TITLE
Just a reminder: markdown formatting

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Archive/LinkC#10]
DO NOT indent your usual text in markdown, or they can be rendered as code. First-line indention is a part of _style_, not a part of _content_.

ALWAYS use an empty line do deliminate paragraphs.

ALWAYS use `====` and `----` which extends to the length of the headings for h1 and h2. (human compatibility).

WHEN IN DOUBT, ALWAYS read GitHub's markdown help.

**Comment by Trickness** [comment]
QAQ Er............

--- 原始邮件 ---

发件人： "Mingye Wang" notifications@github.com
已发： 2015年6月16日 下午2:28
收件人： "AOSC-Dev/LinkC" LinkC@noreply.github.com
主题： [LinkC] Just a reminder: markdown formatting (#10)

DO NOT indent your usual text in markdown, or they can be rendered as code. First-line indention is a part of _style_, not a part of _content_.

ALWAYS use an empty line do deliminate paragraphs.

ALWAYS use `====` and `----` which extends to the length of the headings for h1 and h2. (human compatibility).

WHEN IN DOUBT, ALWAYS read GitHub's markdown help.

---

Reply to this email directly or view it on GitHub:
https://github.com/AOSC-Dev/LinkC/issues/10

**Comment by biergaizi** [comment]
WHEN IN DOUBT, **preview your file first,** and ALWAYS read GitHub's markdown help.
