### ISSUE TITLE
根目录下的readme文件写的各式与内容有问题

### ISSUE THREAD

**Issue by beifangjunma** [AOSC-Archive/LinkC#5]
参考其他开源程序源码包里根目录下的readme文件，写的全是引导怎么去编译，哪些文件夹有什么用，依赖包信息，以及不同国家的人去那里找他们自己的语言版本，关于其他详细信息的readme文件在哪些目录下等    linkc根目录底下的readme就光写了个开发者名字及开发信息，没有各个文件夹的详细用途

**Comment by Trickness** [comment]
well,是不是每个目录下面都建立一个ReadMe.md好一些呢？解释每个文件和目录的作用甚么的

**Comment by wiiiky** [comment]
每个目录都有也不是很必要，就一些重要的目录要有吧。
毕竟现在项目还不是很成熟，有些东西不需要太早考虑，因为以后还可能要改。

不过重要的一点，我觉得应该告诉别人如何参与这个项目，提供一些让别人可以更快熟悉项目的内容

**Comment by beifangjunma** [comment]
readme文件里的说明详细一些

**Comment by Trickness** [comment]
@wiiiky 也就是说在某些必要的目录里面添加ReadMe来解释其作用对吧……我顺便问一下写文档应该怎么写，我失败了两次不止了写文档

**Comment by MingcongBai** [comment]
其实 README 用于介绍项目，而 INSTALL 用于编译指南

-----原始邮件-----
发件人: "张峻锋" notifications@github.com
发送时间: ‎2014/‎7/‎17 13:01
收件人: "AOSC-Dev/LinkC" LinkC@noreply.github.com
主题: Re: [LinkC] 根目录下的readme文件写的各式与内容有问题 (#5)

well,是不是每个目录下面都建立一个ReadMe.md好一些呢？解释每个文件和目录的作用甚么的

**Comment by MingcongBai** [comment]
只是作用的区别，不必想多

-----原始邮件-----
发件人: "beifangjunma" notifications@github.com
发送时间: ‎2014/‎7/‎17 13:10
收件人: "AOSC-Dev/LinkC" LinkC@noreply.github.com
主题: Re: [LinkC] 根目录下的readme文件写的各式与内容有问题 (#5)

readme文件里的说明详细一些

**Comment by wiiiky** [comment]
其实也没有什么固定的写法，唯一的原则就是让用户得到他们想要的信息。

你这样想，什么样的人会看你的项目？然后就按照他们可能的需求写。

比如现在有两类人；
一类是普通用户，他们只是想尝试一下你的程序。你就应该告诉他们如何编译运行。
另一类是想参与该项目的程序员，你应该告诉他们一些代码的实现与设计（详略你自己把握），以及一些要主要的地方（甚至是编码风格之类的）。

**Comment by wiiiky** [comment]
多参考其他开源项目的文档

**Comment by Trickness** [comment]
@wiiiky @TheNextProject 等我补完课就去弄…

**Comment by Trickness** [comment]
真的觉得ReadMe没多大必要………目录名全部看得懂…………

**Comment by LionNatsu** [comment]
我没看懂。。。

Lion Yang

发件人： 张峻锋
发送时间： 2014-07-17 19:22
收件人： AOSC-Dev/LinkC
主题： Re: [LinkC] 根目录下的readme文件写的各式与内容有问题 (#5)
真的觉得ReadMe没多大必要………目录名全部看得懂…………

**Comment by Trickness** [comment]
举例说明

**Comment by LionNatsu** [comment]
整个都不清楚怎么入手，感觉很……没有头绪。我既没有看到期望中的examples、config之类的明确的文件夹，也没有文件去说明这些文件夹的分工。特别是我感觉example和core混杂在了同一个文件夹里。

Lion Yang

发件人： 张峻锋
发送时间： 2014-07-17 19:26
收件人： AOSC-Dev/LinkC
抄送： LionNatsu
主题： Re: [LinkC] 根目录下的readme文件写的各式与内容有问题 (#5)
举例说明

**Comment by Trickness** [comment]
Examples和config都是什么东西？

**Comment by LionNatsu** [comment]
抱歉，我总是会把core以外的东西都归为核心的示例代码，这个习惯很难改啊。config只是个例子，我的意思是，有点难明白这个目录层次结构，个人感觉。

Lion Yang

发件人： 张峻锋
发送时间： 2014-07-17 19:35
收件人： AOSC-Dev/LinkC
抄送： LionNatsu
主题： Re: [LinkC] 根目录下的readme文件写的各式与内容有问题 (#5)
Examples和config都是什么东西？

**Comment by wiiiky** [comment]
如果你实在不想写就算了，反正现在这个项目关注的人也不多。

不过你要知道，“真的觉得ReadMe没多大必要………目录名全部看得懂…………”这个想法是完全错误的，简单地说，难道所有开源项目都只要目录名命名得好就行了？

我建议你还是多多少少写一点，不必太认真

**Comment by Trickness** [comment]
@wiiiky 我英文不行啊…………实在无力，除了用中文写还差不多…

**Comment by wiiiky** [comment]
没有要求你用英文写啊，用中文就好了

**Comment by Trickness** [comment]
我纠结那几个英文不下一个小时，各种百度谷歌有道翻译还生怕语法错误……………………好的，中文的话很简单

**Comment by Trickness** [comment]
把服务端的加完了，ReadMe,md
