### ISSUE TITLE
Unknown BUG in header processing

### ISSUE THREAD

**Issue by Trickness** [AOSC-Archive/LinkC#7]
看上去是一个严重的BUG，起码影响客户端使用。定位在连接时，会出现莫名的数据超长[Header的Length值处于未知状态]。我试图查明这个BUG，但是失败。

**Comment by LionNatsu** [comment]
1.Header没有正确发送；
2.在某些极端情况下Header无法正确接受和解析；
3.对Header的内存操作上存在问题。

建议抓下所有的包进行分析，判断是否为 1、2。

Lion Yang

From: 张峻锋
Date: 2014-08-29 17:50
To: AOSC-Dev/LinkC
Subject: [LinkC] Unkonw BUG (#7)
看上去是一个严重的BUG，起码影响客户端使用。定位在连接时，会出现莫名的数据超长[Header的Length值处于未知状态]。我试图查明这个BUG，但是失败。

**Comment by Trickness** [comment]
主要是坑在它是只在外网测试中几率性出现，然后出现时Length的值每次都一样………

--- 原始邮件 ---

发件人： "LionNatsu" notifications@github.com
已发： 2014年8月29日 下午11:22
收件人： "AOSC-Dev/LinkC" LinkC@noreply.github.com
抄送： "张峻锋" SternWZhang@outlook.com
主题： Re: [LinkC] Unkonwn BUG (#7)

1.Header没有正确发送；2.在某些极端情况下Header无法正确接受和解析；3.对Header的内存操作上存在问题。
建议抓下所有的包进行分析，判断是否为 1、2。

Lion Yang

From: 张峻锋
Date: 2014-08-29 17:50
To: AOSC-Dev/LinkC
Subject: [LinkC] Unkonw BUG (#7)
看上去是一个严重的BUG，起码影响客户端使用。定位在连接时，会出现莫名的数据超长[Header的Length值处于未知状态]。我试图查明这个BUG，但是失败。
—
Reply to this email directly or view it on GitHub.

---

**Comment by LionNatsu** [comment]
那应该就是极端网络情况的处理的问题上了。如果是TCP的话，几个角度：1、极度零散的拆包（甚至要考虑包头的Length四字节被拆掉）；2、特殊的并包没有正确解离、分别处理（在一次recv里，前一个包连着下一个包一起接收）。

**Comment by biergaizi** [comment]
I speak a mouth good English.

**Comment by MingcongBai** [comment]
Eh?

-----原始邮件-----
发件人: "Tom Li" notifications@github.com
发送时间: ‎2014/‎8/‎29 10:40
收件人: "AOSC-Dev/LinkC" LinkC@noreply.github.com
主题: Re: [LinkC] Unknown BUG (#7)

I speak a mouth good English.

**Comment by biergaizi** [comment]
@TheNextProject 

```
Trickness changed the title from Unkonw BUG to Unkonwn BUG 10 hours ago
biergaizi changed the title from Unkonwn BUG to Unknown BUG 4 hours ago
```

**Comment by MingcongBai** [comment]
I didn't see it while it still seemed wrong... let me fix this...

-----原始邮件-----
发件人: "Tom Li" notifications@github.com
发送时间: ‎2014/‎8/‎29 14:10
收件人: "AOSC-Dev/LinkC" LinkC@noreply.github.com
抄送: "Jeff Bai" jeffbaichina@members.fsf.org
主题: Re: [LinkC] Unknown BUG (#7)

@TheNextProject 
Trickness changed the title from Unkonw BUG to Unkonwn BUG 10 hours ago
biergaizi changed the title from Unkonwn BUG to Unknown BUG 4 hours ago

**Comment by MingcongBai** [comment]
Nevermind, did too much maths...

-----原始邮件-----
发件人: "Tom Li" notifications@github.com
发送时间: ‎2014/‎8/‎29 14:10
收件人: "AOSC-Dev/LinkC" LinkC@noreply.github.com
抄送: "Jeff Bai" jeffbaichina@members.fsf.org
主题: Re: [LinkC] Unknown BUG (#7)

@TheNextProject 
Trickness changed the title from Unkonw BUG to Unkonwn BUG 10 hours ago
biergaizi changed the title from Unkonwn BUG to Unknown BUG 4 hours ago
