### ISSUE TITLE
有没有文档简单介绍一下如何设计的

### ISSUE THREAD

**Issue by wiiiky** [AOSC-Archive/LinkC#8]
主要包括支持哪些功能，通信协议的设计

**Comment by Trickness** [comment]
没见得有，实在不行参考下gurgle的文档吧(就是我现在这个协议，github上搜索下就有了

--- 原始邮件 ---

发件人： "Wiky L" notifications@github.com
已发： 2015年2月2日 下午6:20
收件人： "AOSC-Dev/LinkC" LinkC@noreply.github.com
主题： [LinkC] 有没有文档简单介绍一下如何设计的 (#8)

主要包括支持哪些功能，通信协议的设计

---

Reply to this email directly or view it on GitHub:
https://github.com/AOSC-Dev/LinkC/issues/8

**Comment by wiiiky** [comment]
https://github.com/m13253/gurgle
这个？
可是这个也没有说明什么啊。
另外我想知道你要实现哪些功能.

**Comment by Trickness** [comment]
………………虽然你答到点子上来了………
这货就丢我一份这个文档就跑去高考了囧rz
还有请走AOSC-Dev/LinkC的Developing分支……我在里面稍微有点开发文档(虽然不知道有什么用)，现在的开发也在这里面(虽然有点见不得人，个人Py水平确实不高

现在在设计登录部分……

简而言之，就是使用的文本协议(基于JSON)，文档中现在只列举了登录部分的资料………并且我连登录部分的资料都看不懂(等下单独发邮件说)

--- 原始邮件 ---

发件人： "Wiky L" notifications@github.com
已发： 2015年2月2日 下午6:52
收件人： "AOSC-Dev/LinkC" LinkC@noreply.github.com
抄送： "张峻锋" SternWZhang@outlook.com
主题： Re: [LinkC] 有没有文档简单介绍一下如何设计的 (#8)

https://github.com/m13253/gurgle
这个？
可是这个也没有说明什么啊。
另外我想知道你要实现哪些功能.

---

**Comment by wiiiky** [comment]
我想可以的话我也可以做一点，可是如果要做什么都不清楚的话，就没法开始了

**Comment by MingcongBai** [comment]
我已设置默认分支为 Developing 。
