### ISSUE TITLE
Deprecate Old Branch

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Archive/LinkC#9]
Don't know if I've got this right, if LinkC is switching to Gurgle for the future... Try and clean up the old branch shall we?

**Comment by Trickness** [comment]
Er...………………………………………………Okay

--- 原始邮件 ---

发件人： "Jeff Bai" notifications@github.com
已发： 2015年2月2日 下午11:17
收件人： "AOSC-Dev/LinkC" LinkC@noreply.github.com
主题： [LinkC] Deprecate Old Branch (#9)

Don't know if I've got this right, if LinkC is switching to Gurgle for the future... Try and clean up the old branch shall we?

---

Reply to this email directly or view it on GitHub:
https://github.com/AOSC-Dev/LinkC/issues/9

**Comment by MingcongBai** [comment]
Just make sure of it... BTW I made Docs into a submodule linking to "gurgle".

-----原始邮件-----
发件人: "张峻锋" notifications@github.com
发送时间: ‎2015/‎2/‎2 8:20
收件人: "AOSC-Dev/LinkC" LinkC@noreply.github.com
抄送: "Jeff Bai" jeffbaichina@members.fsf.org
主题: Re: [LinkC] Deprecate Old Branch (#9)

Er...………………………………………………Okay 

--- 原始邮件 --- 

发件人： "Jeff Bai" notifications@github.com 
已发： 2015年2月2日 下午11:17 
收件人： "AOSC-Dev/LinkC" LinkC@noreply.github.com 
主题： [LinkC] Deprecate Old Branch (#9) 

Don't know if I've got this right, if LinkC is switching to Gurgle for the future... Try and clean up the old branch shall we? 

---

Reply to this email directly or view it on GitHub: 
https://github.com/AOSC-Dev/LinkC/issues/9
